// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB47LGGd8XBMpAVWU1XKqmx0BcdQH4O3fA',
    appId: '1:927312511652:web:1588301500b44045e29c31',
    messagingSenderId: '927312511652',
    projectId: 'healthcare-23678',
    authDomain: 'healthcare-23678.firebaseapp.com',
    storageBucket: 'healthcare-23678.appspot.com',
    measurementId: 'G-JTP4VJ6JSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmd01qpzbpoNFMEPnroA4cEkBfmqC2nHU',
    appId: '1:927312511652:android:0210624b9b16469ee29c31',
    messagingSenderId: '927312511652',
    projectId: 'healthcare-23678',
    storageBucket: 'healthcare-23678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtIONy9n7rWOR907Qh0_ySAbU-7y9l7qU',
    appId: '1:927312511652:ios:df94749dbaed4712e29c31',
    messagingSenderId: '927312511652',
    projectId: 'healthcare-23678',
    storageBucket: 'healthcare-23678.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtIONy9n7rWOR907Qh0_ySAbU-7y9l7qU',
    appId: '1:927312511652:ios:df94749dbaed4712e29c31',
    messagingSenderId: '927312511652',
    projectId: 'healthcare-23678',
    storageBucket: 'healthcare-23678.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB47LGGd8XBMpAVWU1XKqmx0BcdQH4O3fA',
    appId: '1:927312511652:web:e34eddc63f628b8fe29c31',
    messagingSenderId: '927312511652',
    projectId: 'healthcare-23678',
    authDomain: 'healthcare-23678.firebaseapp.com',
    storageBucket: 'healthcare-23678.appspot.com',
    measurementId: 'G-BKLYZFTEKQ',
  );
}
